### ISSUE TITLE
Finalise XCA deployment process

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#1271]
Proper deployment branches.  @alanchristie to map out.

~~(Possibly pull down code as required - @conorfwild to investigate.)~~

Target loader should check XCA version upon parsing an upload.

XCA should write XCA version into output. 

@ConorFWild suggested check-version-upon-execution in XCA.

**Comment by tdudgeon** [comment]
We've been playing around with getting info on the Git repo.
We now have code that can generate info like this (which would be included in the metadata YAML):

```
xca-version:
  origin_url: git@github.com:xchem/xchem-align.git
  branch: master
  sha: 3d0fea19b176ffe800d011d18ac2f295c239376e
  tag: null
  dirty: true
```

This raises a few questions:

1. The assumption is that the repo we are working on has a remote called `origin` and the target loader would only accept data from an origin of `xchem/xchem-align.git`.
2. In my case I'm working in the directory of the checked out data, but in the case of the users running at Diamond with the environment that Conor has set up this may not be the case. @ConorFWild can you confirm?
3. We need a policy on what is allowed. e.g. on production Fragalysis you must be on a specific branch (that has been blessed) and the code must not be dirty. But on any other Fragalysis instances (e.g. non prod) any values are allowed. @Waztom can you confirm the policy that is required.

**Comment by alanbchristie** [comment]
Can we use blank values or empty strings instead of `null` for missing tags? An empty property is interpreted as `None` anyway, and the lack of a value is (imo) less distracting: -

```yaml
xca-version:
  origin_url: git@github.com:xchem/xchem-align.git
  branch: master
  sha: 3d0fea19b176ffe800d011d18ac2f295c239376e
  tag:
  dirty: true
```
I also think the `branch` may be unnecessary when you have a commit reference (sha) as you can checkout using a commit ref.
