### ISSUE TITLE
When crystal is superceded 

### ISSUE THREAD

**Issue by ConorFWild** [m2ms/fragalysis-frontend#1280]
This occurred with A71EV2A (/dls/labxchem/data/lb32627/lb32627-66/processing/analysis/xchem_align_uploads) when trying to upload a upload_2 iteration.

```yaml
  A71EV2A-x0469:
    type: model_building
    last_updated: '2024-01-17 09:48:00'
    refinement_outcome: 4 - CompChem ready
    crystallographic_files:
      xtal_pdb:
        file: upload_2/crystallographic_files/A71EV2A-x0469/A71EV2A-x0469.pdb
        sha256: 0c8184de9a7ff34904206b916cc8678e35fe195b6f5702a448bd42e12ac34107
      xtal_mtz:
        file: upload_2/crystallographic_files/A71EV2A-x0469/A71EV2A-x0469.mtz
        sha256: 8cad741f97f1618305fa245f8c07af35d74aa7214d54744c7743f87f4d9febba
      ligand_cif:
        file: upload_1/crystallographic_files/A71EV2A-x0469/A71EV2A-x0469.cif
        sha256: 2dc6efdcaadafdfee97715c859953727adeb7452e779b751d3ede47701913ccd
        smiles: CC(C)N1CCN(c2ncccn2)CC1
      panddas_event_files:
      - file: upload_2/crystallographic_files/A71EV2A-x0469/A71EV2A-x0469_1_A_147.ccp4
        sha256: e2438159116d3735bcffa225b9bbca497dae609c965b14444ff273f478b9b3f7
        model: '1'
        chain: A
        res: 147
        index: 1
        bdc: 0.28
    status: supersedes
```

However the corresponding data is not actually copied:

```
ls upload_2/crystallographic_files/A71EV2A-x0469
A71EV2A-x0469.mtz  A71EV2A-x0469.pdb

```

This causes errors when creating new alignments

```
FileNotFoundError: [Errno 2] Failed to open upload_2/crystallographic_files/A71EV2A-x0469/A71EV2A-x0469_1_A_147.ccp4: No such file or directory

```

This likely is a result of broken logic in collator.py around line in Collator:_copy_files. This logic is VERY complicated and so this is unlikely to be a quick fix for me @phraenquex however iterations are unlikely to work without it so suggest this is fixed urgently.
