### ISSUE TITLE
Review "ref_datasets" (config.yaml) - definition and use

### ISSUE THREAD

**Issue by tdudgeon** [m2ms/fragalysis-frontend#1298]
In Ryan's A71EV2A data the `reference_aligned_files` of the metadata output is empty.

**Comment by tdudgeon** [comment]
I think I might have spotted the problem. Ryan's config looks like this:
```
target_name: A71EV2A
base_dir: /
output_dir: /dls/labxchem/data/lb32627/lb32627-66/processing/analysis/xchem_align_uploads
ref_datasets: 
  - reference/A71_2A_x0090_ref_7_monomer
  - reference/small_cell
inputs:
  - dir: dls/labxchem/data/lb32627/lb32627-66
    type: model_building
    soakdb: processing/database/soakDBDataFile.sqlite
    panddas_event_files:
    - processing/analysis/pandda_2_20231020_ranking_test/pandda/analyses/pandda_inspect_events.csv
    - processing/analysis/pandda2_first_500_17_10_23/pandda/analyses/pandda_inspect_events.csv
    - processing/analysis/pandda2_remaining_screen_smallcell_2023-12-05/analyses/pandda_inspect_events.csv
  - dir: dls/labxchem/data/lb32627/lb32627-66/processing/analysis/xchem_align_uploads/reference
    type: manual
```

The `ref_datasets` section is wrong. They should just list the crystal names (e.g. the `reference/` bits should be removed). 

But as *aligner* did not blow up with this suggests things are not quite right.
There should be validation that the `ref_datasets` are present.

But also, it looks like the ref datasets are also defined in the `crystalforms.yaml` (now renamed to `assemblies.yaml`) so does this need to defined at all in the `config.yaml`?
