### ISSUE TITLE
Test multiple uploads

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#1311]
Already tested, this is place-holder for later versions

**Comment by Waztom** [comment]
@tdudgeon has tested, but is waiting on @ConorFWild to sort out the superseding of reference datasets challenge (that will break things if ref set superseded).

**Comment by phraenquex** [comment]
Needs #1280 to be fixed first.

**Comment by phraenquex** [comment]
@tdudgeon, suggestion/request: `collate.py` should work out which upload directory to use, and create as required.

Specifically, once a file has been uploaded, the relevant upload directory needs a flag (`status.yaml`?) that it has been uploaded, etc.  (Or I suppose `collate.yaml` could ping Fragalysis...?!)

If this belongs to a new/different ticket, please update as relevant. 

What DOES need clarifying are the [Collating files instruction](https://github.com/xchem/xchem-align/blob/master/USER-GUIDE.md#3-collating-files): it looks like something is missing, namely how you tell `collate.py` which upload directory to use.

**Comment by tdudgeon** [comment]
@phraenquex I think the instructions are clear, but what was missing were instructions for subsequent versions, so I added this (which also makes it even clearer): https://github.com/xchem/xchem-align/blob/master/USER-GUIDE.md#6-creating-subsequent-versions

The current mechanism is designed for safety. Creating a new version is something that is explicitly decided on by the user, not by some software making a guess on this.
Once we have the *uploader* tool working we can make this a bit smarter, by locking down the `upload_?` directory once it has been successfully uploaded and creating the next `upload_?` directory.

**Comment by Waztom** [comment]
This is linked to #1338 - pending @ConorFWild code changes.

**Comment by Waztom** [comment]
@ConorFWild has made changes and is ready for assessing in staging/other target uploads.

**Comment by mwinokan** [comment]
@Waztom was testing this with Ryan's A71EV2A dataset.

@kaliif to test with older upload_1 and upload_2 datasets for A71EV2A

**Comment by mwinokan** [comment]
Jasmin is attempting this for CHIKV_Mac, her issues are coupled with the PDB upload (which they might not need to be). She is attempting an upload_2 which only contains 'manual'/RCSB PDBs.

To troubleshoot this effectively, we should prepare some a unit test data set from a successful upload_1. @tdudgeon says he did an upload_2 about a month ago, but we need to test again. 

@tdudgeon please repeat the tests with same procedure as before: include some crystals in the 'exclude' list like before.

**Comment by mwinokan** [comment]
Jasmin has successfully uploaded an Xchem-data-only upload_2 on staging, it should now work in production too

**Comment by mwinokan** [comment]
@tdudgeon has provided @ConorFWild with a test data set to work on the superseding issue

**Comment by mwinokan** [comment]
@ConorFWild has been working on the superseding issue:

When data was superseded no alignments were generated for superseded datasets, and some abnormalities in conformer site formation. No algorithm logic changes needed, but the implementation did change technically (logic to decide whether a new site is needed).

A solution has been found: implemented on an XCA branch, it works locally on the dataset (which one?) that was giving Tim issues. The fix does cause changes to the uploader interface (the output metadata differs).

A 'version' key has been added to the dataset output in the metadata. @ConorFWild please provide a spec for @kaliif to update the loader

**Comment by ConorFWild** [comment]
Changes:

The meta_aligner.yaml and fs_model.yaml now have an additional key in the heirarchy leading to aligned files

```yaml
# meta_aligner.yaml
...
    aligned_files:
      A:
        '201':
          '1':  # New key
            A71EV2A-x0528+A+147+1: {structure: upload_1/aligned_files/A71EV2A-x0450/A71EV2A-x0450_A_201_1_A71EV2A-x0528+A+147+1.pdb,
...

# fs_model.yaml
...
alignments:
  A211:
    A:
      '147':
        '1': # New key
          aligned_artefacts:
            A71EV2A-x0541+A+147+1: ../../Downloads/lb32627-66/upload_1/aligned_files/A211/A211_A_147_1_A71EV2A-x0541+A+147+1_artefacts.pdb
...
```
