### ISSUE TITLE
New config.yaml spec

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#1332]
* `base_dir` - make it optional, and default to `emptystring`.  (And remove from instructions - make people use absolute paths.
* `ref_datasets` - rename to `reference_conformations`
* add `model_building` card to `inputs`
 

### Needs clarifying
* what is `target_name` used for?
* _must_ there be a `reference_conformation` for each "major class of conformation"?  Or is it merely recommended?
* 

### Inputs should be:

```
inputs:    # what's currently type "model_building"

 - type: xchem        # what's currently "model_building"
      code_prefix:  "m"      # what fragalysis should prefix to the short code (used by uploader, ignored by XCA)
      code_prefix_tooltip:   "MERS structures"     # for fragalysis to display in the short code tooltip  (ignored by XCA)
      dir:  /dls/labxchem/data/lb32633/lb32633-6/processing      # absolute maximum common path, no assumptions
      soakdb:   analysis/database/soakDBDataaFile.sqlite
      models:   analysis/model_building     # explicit path to models
      exclude:  [ ]
      panddas_event_files: 
         - analysis/panddas/20231124_pandda2/analyses/pandda_inspect_events.csv
         - analysis/panddas/....
      panddas_missing_ok:   [ ]

- type: conventional:
      code_prefix:  "
      dir:  /absolute/path/to/directory/of/model/subdirectories 
      short_codes:           # tuples of [subdirname, shortcodetouse] (Ignored by XCA)
         - [CHIKV_MacB-x0257-GS,  1a-apo, A265]          # include only one observation of one canonical site, containing A265]
         - [CHIKV_MacB-x0257-GS,  MacB-x0300+A+401+1]   # include all observations of this canonical site
         - [CHIKV_MacB-x0113-GS,  2a-apo]                    # include all observations of all canonical sites (possibly not useful)
      mtz_missing_ok:  [ ]

- type:  pdb_downloads:
     dir:  /absolute/path/to/directory/of/downloads/no/sub/dirs
     mtz_missing_ok:  [ ] 

- type: pdb_codes: 
     codes:  [ 60wt, 6w7h, .... ]
```

Some spec to be added for `pdb_downloads` and `pdb_codes`, for how to download things and generate electron density.
