### ISSUE TITLE
F/E functionality of original experimental data paths to aid in upload debugging loop 

### ISSUE THREAD

**Issue by mwinokan** [m2ms/fragalysis-frontend#1497]
To shorten the feedback loop between alignment, upload, and reviewing of data in case there are faulty observations, @phraenquex suggests that we need some UI to be able to see the paths to the original experimental data for each observation.

This will require collator/aligner changes in XCA @tdudgeon

F/E UI specs still to follow @matej-vavrek

**Comment by phraenquex** [comment]
What is needed is the frontend to know the original location of the PDB file - the thing that's in soakDB.  

@tdudgeon needs to add to XCA/yamls
@kaliif needs to load and serve by API
@matej-vavrek needs to stick it into the extended view (probably a [copy] button next to the longcode)

**Comment by tdudgeon** [comment]
Collator now adds `source_file` property to the `crystallographic_files` entries.
Example:

```
    crystallographic_files:
      xtal_pdb:
        file: upload_1/crystallographic_files/A71EV2A-x0450/A71EV2A-x0450.pdb
        sha256: dec53789027de5ffc0eb42b4158c1023f96d59142291e1b67676eeaef4a17df2
        source_file: data/lb32627-66/inputs/dls/labxchem/data/lb32627/lb32627-66/processing/analysis/model_building/A71EV2A-x0450/Refine_0004/refine_4.split.bound-state.pdb
      xtal_mtz:
        file: upload_1/crystallographic_files/A71EV2A-x0450/A71EV2A-x0450.mtz
        sha256: 48ce6ce332b71246126912d05ce3ac1ab1452b9203c382c279c2fb933c4ca178
        source_file: data/lb32627-66/inputs/dls/labxchem/data/lb32627/lb32627-66/processing/analysis/model_building/A71EV2A-x0450/Refine_0004/refine_4.mtz
      ligand_cif:
        file: upload_1/crystallographic_files/A71EV2A-x0450/A71EV2A-x0450.cif
        sha256: d55dadae7fb0d7638b249b27d03c1f3207ab6065527fd6ca2d067c63759a9ee1
        source_file: data/lb32627-66/inputs/dls/labxchem/data/lb32627/lb32627-66/processing/analysis/model_building/A71EV2A-x0450/compound/Z100642432.cif
        smiles: CN(C)C(=O)c1ccc(F)cc1Br
        ligand_name: LIG
      ligand_binding_events:
      - file: upload_1/crystallographic_files/A71EV2A-x0450/A71EV2A-x0450_1_A_201.ccp4
        sha256: 56d493d405bd9bfa8105b7bba96adb3741bdac7ea13d96293fcec6f8bc59a780
        source_file: data/lb32627-66/inputs/dls/labxchem/data/lb32627/lb32627-66/processing/analysis/pandda2_remaining_screen_smallcell_2023-12-05/processed_datasets/A71EV2A-x0450/A71EV2A-x0450-event_2_1-BDC_0.9_map.native.ccp4
        model: '1'
        chain: A
        res: 201
        index: 2
        bdc: 0.9
```

Commit: https://github.com/xchem/xchem-align/commit/c6e6ded4a29a63a55a16d8808f7d2add8be2491e
