### ISSUE TITLE
CrystalForm sites mis-assigned (?)

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#1511]
@ConorFWild this appears to be a bug - please confirm or clarify.

In the CHIKV MacB dataset, one crystal (c0399) has the same ligand show up in the same site in 7 chains;  yet in `meta_aligner.yaml`, they're all assigned to the same `xtalform_site`.  Here's the chunk of yaml, with the seven observations bolded:

> xtalform_sites:
>   CHIKV_MacB-x0270/A/304/1:
>     canonical_site_id: CHIKV_MacB-x0300+A+401+1
>     crystallographic_chain: A
>     members: [CHIKV_MacB-x0270/A/304/1, CHIKV_MacB-x0281/C/304/1, CHIKV_MacB-x0289/C/401/1,
>       CHIKV_MacB-x0294/A/401/1, CHIKV_MacB-x0294/B/304/1, CHIKV_MacB-x0295/A/401/1,
>       CHIKV_MacB-x0300/A/401/1, CHIKV_MacB-x0300/C/304/1, CHIKV_MacB-x0305/C/304/1,
>       CHIKV_MacB-x0312/A/304/1, CHIKV_MacB-x0312/C/401/1, CHIKV_MacB-x0312/D/401/1,
>       CHIKV_MacB-x0314/B/401/1, CHIKV_MacB-x0314/C/304/1, CHIKV_MacB-x0314/D/401/1,
>       CHIKV_MacB-x0316/C/304/1, CHIKV_MacB-x0317/C/401/1, CHIKV_MacB-x0353/A/304/1,
>       CHIKV_MacB-x0353/B/304/1, CHIKV_MacB-x0394/D/304/1, CHIKV_MacB-x0398/C/401/1,
>       **CHIKV_MacB-x0399/A/401/1, CHIKV_MacB-x0399/A/402/1, CHIKV_MacB-x0399/B/401/1,**
>       **CHIKV_MacB-x0399/B/402/1, CHIKV_MacB-x0399/C/308/1, CHIKV_MacB-x0399/C/309/1,**
>       **CHIKV_MacB-x0399/D/304/1**, CHIKV_MacB-x0404/A/401/1, CHIKV_MacB-x0404/C/304/1,
>       CHIKV_MacB-x0406/A/401/1, CHIKV_MacB-x0406/B/304/1, CHIKV_MacB-x0436/A/401/1,
>       CHIKV_MacB-x0436/C/304/1, CHIKV_MacB-x0441/D/401/1, CHIKV_MacB-x0477/A/401/1

I thought they need to be seven different `xtalform_sites` - bug or misunderstanding?

If a bug, double-check the conformer sites too - because it's surprising that all seven observations should be in the same conformer site (which they are).

Yaml file attached (as .yaml.txt).

[meta_aligner.yaml.txt](https://github.com/user-attachments/files/16945554/meta_aligner.yaml.txt)

This should have been a green release, but has to bleed into mint, and we'll need to work out how to mitigate later.  (Maybe some database hacking for @kaliif.)

**Comment by phraenquex** [comment]
Asking @tdudgeon :  if XCA is rerun on an untouched input, will the new yamls be correctly processed (by collator)?

Tim says:  if it's run in a new upload, then it should do - but hasn't been tested yet, so expect corner cases.

**Comment by mwinokan** [comment]
@ConorFWild has been working on the new CrystalFormSites algorithm and the CanonicalSite residue output in tandem. A draft implementation has been made that is being tested

**Comment by ConorFWild** [comment]
@phraenquex 

Both issues appear addressed in [418af07](https://github.com/xchem/ligand_neighbourhood_alignment/commit/418af0710f172309af08879ca331198b022d51b8)

This method correctly addresses the misassignment of ligand chain ID, as demonstrated by the following image and excerpt from the crystalform site yaml.

![Image](https://github.com/user-attachments/assets/7c485f9f-14e2-47e9-aeb9-15f69daa0029)


```yaml

...

CHIKV_MacB-x0305/C/304/1:
  canonical_site_id: CHIKV_MacB-x2344+B+401+1
  crystallographic_chain: C
  members:
  - CHIKV_MacB-x0305/C/304/1
  - CHIKV_MacB-x0317/C/401/1
  - CHIKV_MacB-x0398/C/401/1
  - CHIKV_MacB-x0404/C/304/1
  - CHIKV_MacB-x0436/C/304/1
  - CHIKV_MacB-x0505/C/401/1
  - CHIKV_MacB-x0540/C/401/1
  - CHIKV_MacB-x0543/C/401/1
  - CHIKV_MacB-x0585/C/401/1
  - CHIKV_MacB-x0620/C/401/1
  - CHIKV_MacB-x0732/C/401/1
  - CHIKV_MacB-x0760/C/308/1
  - CHIKV_MacB-x0858/C/308/1
  - CHIKV_MacB-x0888/C/401/1
  - CHIKV_MacB-x0927/C/401/1
  - CHIKV_MacB-x0934/C/308/1
  - CHIKV_MacB-x0997/C/401/1
  - CHIKV_MacB-x1103/C/308/1
  - CHIKV_MacB-x1131/C/308/1
  - CHIKV_MacB-x1135/C/401/1
  - CHIKV_MacB-x1185/C/304/1
  - CHIKV_MacB-x1188/C/401/1
  - CHIKV_MacB-x1198/C/308/1
  - CHIKV_MacB-x1203/C/310/1
  - CHIKV_MacB-x1315/C/304/1
  - CHIKV_MacB-x1331/C/401/1
  - CHIKV_MacB-x1371/C/403/1
  - CHIKV_MacB-x1421/C/304/1    # 
  - CHIKV_MacB-x1483/A/304/1    # 
  - CHIKV_MacB-x1487/C/401/1
  - CHIKV_MacB-x1491/A/304/1
  - CHIKV_MacB-x2129/C/308/1
  - CHIKV_MacB-x2352/C/401/1
  - CHIKV_MacB-x2343/C/401/1
  - CHIKV_MacB-x2346/C/401/1
  - CHIKV_MacB-x2437/C/403/1
  xtalform_id: P31-4fold-NCS

...

```
