### ISSUE TITLE
Redirect legacy Mpro link to v2 target

### ISSUE THREAD

**Issue by mwinokan** [m2ms/fragalysis-frontend#1735]
In cases where the legacy target has been superseded by a target on the v2 stack, could we add a warning toaster on the legacy target with a link to the new target?

@boriskovar-m2ms could you comment on whether the toaster code can be easily ported from v2 to the v1 stack?

@alanbchristie is an environment variable the best way to handle this? I am not suggesting an automatic detection of superseding rather a specific mapping of v1 targets to v2 via some tuples that I can provide.

**Comment by alanbchristie** [comment]
We could use the presence of `LEGACY_URL` (also available in the **context**) to at least signal that there is another stack of course. Does this help?

**Comment by mwinokan** [comment]
This could be used to generally show a warning on the legacy stack, but this wouldn't allow for a link to the new target for users visiting the legacy Mpro specifically I guess?

**Comment by mwinokan** [comment]
@boriskovar-m2ms suggests hardcoding some behaviour on the legacy stack to add a warning toaster for Mpro specifically.

@phraenquex asks if there is a way to change the URL routing instead, preferably without changing the legacy code. @boriskovar-m2ms says that since this is a single page application the b/e doesn't know which target the user is trying to access.

@boriskovar-m2ms says that there is some extra effort to find the correct branches and data for local testing, while the code changes themselves are easy. 

@mwinokan asks if there is a way to catch the specific URL in nginx and reroute it instead of changing the stack

@alanbchristie clarifies that once the request is in STFC it goes to the cluster's nginx, and @alanbchristie is unsure if a redirect can happen for a specific URL pattern.

@tdudgeon says that if the legacy URLS always start with the same prefix then nginx should be able to be used for this.

The desired behaviour would be that nginx in the legacy stack returns a 301 for this specific URL:
- IN `https://fragalysis-legacy.xchem.diamond.ac.uk/viewer/react/preview/target/Mpro`
- OUT `https://fragalysis.diamond.ac.uk/viewer/react/preview/target/CoV-Mpro/tas/lb32627-272`

@phraenquex asks that @alanbchristie please spends an hour or two (no more) to see if the above can be handled in nginx (easily)

**Comment by mwinokan** [comment]
@mwinokan chatgpt says:
```
server {
    listen 80;
    server_name fragalysis-legacy.xchem.diamond.ac.uk;

    # Redirect specific URL to the new location
    location = /viewer/react/preview/target/Mpro {
        return 301 https://fragalysis.diamond.ac.uk/viewer/react/preview/target/CoV-Mpro/tas/lb32627-272;
    }

    # Other server configuration...
}
```

**Comment by alanbchristie** [comment]
By adding the following `data` section to the `ingress-nginx-controller` **ConfigMap** in the Production cluster's `ingress-nginx` **Namespace** (to allow snippets and set the risk level to the highest [allowing everything]): -

```yaml
data:
  allow-snippet-annotations: "true"
  annotations-risk-level: Critical
```

And then _bouncing_ each nginx controller **Pod** (to pickup the new configuration), we can then set a `server-snippet` in the `stack` **Ingress** of the `production-stack` (Legacy) **Namespace**: -


```yaml
nginx.ingress.kubernetes.io/server-snippet: |
  location /viewer/react/preview/target/Mpro {
    return 301 https://fragalysis.diamond.ac.uk/viewer/react/preview/target/CoV-Mpro/tas/lb32627-272;
  }
```

> All of this was done on the Rancher NGINX controller version `rancher/nginx-ingress-controller:nginx-1.11.5-rancher1`
>
> For details of all configuration parameters see: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#allow-snippet-annotations

**Comment by mwinokan** [comment]
@alanbchristie please redirect this link as well:

`https://fragalysis-legacy.xchem.diamond.ac.uk/viewer/react/preview/target/Mpro/tas/lb18145-1`

**Comment by alanbchristie** [comment]
I am worried that the redirection has the same path and may be being trapped by the first redirection or I am missing something. Without any modification when I navigate directly to the URL you provided ... 

https://fragalysis-legacy.xchem.diamond.ac.uk/viewer/react/preview/target/Mpro/tas/lb18145-1

I am already directed to: -

https://fragalysis.diamond.ac.uk/viewer/react/preview/target/CoV-Mpro/tas/lb32627-272


Where am I going from and where am I going to?

**Comment by mwinokan** [comment]
Thanks @alanbchristie. Maybe @boriskovar-m2ms needs to weigh in. The behaviour that's not being redirected is when you click the MPro link in the target list on the legacy stack.

**Comment by boriskovar-m2ms** [comment]
It's because we are within a single page application so when you are going from the landing page you are not hitting nginx so you're bypassing redirection mechanism.

**Comment by mwinokan** [comment]
@alanbchristie 

Since all legacy targets can also be accessed from the v2 landing page can we just redirect the landing page for the legacy stack straight to v2?

**Comment by boriskovar-m2ms** [comment]
If you go to the landing page of V2 stack and then you go from there to V1 stack to view legacy stack then you can go to landing page of V1 from there via Home option in the menu or clicking on the target name.

**Comment by alanbchristie** [comment]
Great - I'm afraid I do not understand what it is that needs doing. There's an **nginx** in the cluster and **Ingresses** that are used to control where paths are directed to in the Pods.

Maybe a quick chat and demonstration?

**Comment by mwinokan** [comment]
@boriskovar-m2ms I just spoke to Alan and he'll reach out to you briefly, it may be that we need a f/e solution to this after all.

**Comment by alanbchristie** [comment]
@boriskovar-m2ms believes the redirection requires a f/e patch. As you’ve seen - the f/e is not calling out to the b/e or making a separate URI call. You can refresh the page but any _automatic_ solution will need f/e changes.

**Comment by boriskovar-m2ms** [comment]
I don't know if I remember this stuff correctly but are there (V1 stack) private targets? I.e. targets that user can see only after they're logged in (if yes I don't know if I can solve this). When looking for targets which are uploaded to V2 should I use `target name` or `display name`? What in case if there are more targets with same name (like in case of `Mpro` - and in this specific case legacy target is `Mpro` but new one(s) are called something like `CoV-Mpro`)?

**Comment by mwinokan** [comment]
@alanbchristie has implemented:

1. If you go to the legacy homepage you are redirected to the v2 homepage

`https://fragalysis-legacy.xchem.diamond.ac.uk/viewer/react/landing` --> `https://fragalysis.diamond.ac.uk/viewer/react/landing`

2. In the v2 homepage: you click on the v1 Mpro link you are sent to the v2 target (already implemented)

3. If you click any other legacy target you are taken directly to the v1 target (should not be broken by 1)

@mwinokan to verify that this is working and enumerate more superseded targets

**Comment by alanbchristie** [comment]
The (legacy) `production-stack` **Namespace** **Ingress** is modified to redirect the _landing_ page to v2 with the following addition to the `nginx.ingress.kubernetes.io/server-snippet`: -

```
location /viewer/react/landing {
  return 301 https://fragalysis.diamond.ac.uk/viewer/react/landing;
}
```

The new _snippet_ content is: -

```yaml
nginx.ingress.kubernetes.io/server-snippet: |
  location /viewer/react/landing {
    return 301 https://fragalysis.diamond.ac.uk/viewer/react/landing;
  }
  location /viewer/react/preview/target/Mpro {
    return 301 https://fragalysis.diamond.ac.uk/viewer/react/preview/target/CoV-Mpro/tas/lb32627-272;
  }
```

For reference, the complete **Ingress** definition is: -

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stack
  namespace: production-stack
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-nginx-production
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/server-snippet: |
      location /viewer/react/landing {
        return 301 https://fragalysis.diamond.ac.uk/viewer/react/landing;
      }
      location /viewer/react/preview/target/Mpro {
        return 301 https://fragalysis.diamond.ac.uk/viewer/react/preview/target/CoV-Mpro/tas/lb32627-272;
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fragalysis-legacy.xchem.diamond.ac.uk
      secretName: stack-tls
  rules:
    - host: fragalysis-legacy.xchem.diamond.ac.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stack
                port:
                  name: http
```

> Why do I need this? Should we ever have to deploy a new legacy the playbooks may replace the **Ingress** with its original content. If this ever happens we do have the content pasted here for that can be used to recreate its current behaviour.
